import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Memo from '../public/comp/memo'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [state, setState] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <input type='text' onChange={(e) => setState(e.target.value)}/>
          <Memo arr={state}/>
        </h1>
      </main>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
